version: '3.9'

volumes:
    postgres_data: {}

networks:
  default:
   name: britecorehpnet

services:
  backend:
    image: edpessoa/bc-back
    depends_on:
      - postgres
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    image: edpessoa/bc-front
    ports:
      - "80:80"
    depends_on:
      - backend
