version: '3.3'

volumes:
    postgres_data: {}


services:
  backend:
    build:
      context: ./backend
    image: edpessoa/bc-back
    depends_on:
      - postgres
#    volumes:
#      - ./backend:/app
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  postgres:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: edpessoa/bc-front
    ports:
      - "80:80"
    depends_on:
      - backend



