# Generated by Django 3.1.2 on 2021-03-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200)),
                (
                    "payload_field",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="RiskTypeFields",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=200)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "field_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risks.fieldtype",
                    ),
                ),
                (
                    "risk_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="risks.risktype"
                    ),
                ),
            ],
        ),
    ]
