# Generated by Django 3.1.2 on 2021-03-21 16:23
import json
from django.db import migrations


def add_default_field_types(apps, schema_editor):
    FieldType = apps.get_model("risks", "FieldType")

    text = FieldType(type="text")
    text.save()
    number = FieldType(type="number")
    number.save()
    date = FieldType(type="date")
    date.save()
    enum = FieldType(type="enum", payload_field="options")
    enum.save()


def _add_field_to_risk_type(apps, risk, field_type, field_name, payload):
    RiskTypeFields = apps.get_model("risks", "RiskTypeFields")
    risk_fields = RiskTypeFields(
        risk_type=risk,
        field_type=field_type,
        field_name=field_name,
        payload=payload,
    )
    risk_fields.save()


def _add_risk_type(apps, name, risk_type_fields):
    RiskType = apps.get_model("risks", "RiskType")
    FieldType = apps.get_model("risks", "FieldType")
    default_fields = {field.type: field for field in FieldType.objects.all()}
    rt = RiskType(name=name)
    rt.save()
    options = {"options": ["option0", "option1", "option2", "option3"]}

    for field in risk_type_fields:
        _add_field_to_risk_type(
            apps,
            rt,
            default_fields[field["type"]],
            field["name"],
            json.dumps(options) if field["type"] == "enum" else None,
        )


def _populate_db(apps):
    risk_types = {
        "mean": [
            {
                "type": "text",
                "name": "Name",
            },
            {
                "type": "number",
                "name": "Value",
            },
            {
                "type": "date",
                "name": "Due"
            },
        ],
        "simple": [
            {
                "type": "text",
                "name": "Model",
            },
            {
                "type": "enum",
                "name": "Color",
            },
        ],
        "comp": [
            {
                "type": "text",
                "name": "Description",
            },
            {
                "type": "number",
                "name": "Quantity",
            },
            {
                "type": "date",
                "name": "Start"
            },
            {
                "type": "enum",
                "name": "Options",
            },
        ],
    }
    rtf_to_add = ["mean", "simple", "comp"]
    for r in rtf_to_add:
        _add_risk_type(apps, r, risk_types[r])


def add_example_risk_type(apps, schema_editor):
    RiskType = apps.get_model("risks", "RiskType")
    FieldType = apps.get_model("risks", "FieldType")

    default_fields = {field.type: field for field in FieldType.objects.all()}
    general = RiskType(name="general")
    general.save()

    _add_field_to_risk_type(apps, general, default_fields["text"], "name", None)
    _add_field_to_risk_type(apps, general, default_fields["number"], "reference", None)
    _add_field_to_risk_type(apps, general, default_fields["date"], "created", None)
    options = {"options": ["red", "blue", "green"]}
    _add_field_to_risk_type(
        apps, general, default_fields["enum"], "color", json.dumps(options)
    )
    _populate_db(apps)


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_default_field_types),
        migrations.RunPython(add_example_risk_type),
    ]
